name: Publish Wiki

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Publish documentation to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki
          commit-message: Update wiki ${{ github.event.pull_request.merge_commit_sha }}
